id: A8788C986
title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
type: translation
pechas:
- I355FD61F
- IF42747AA
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:45:17.194099
  last_modified_at: 2023-01-04 11:45:17.194112
  collections:
  - Dorje Dechen Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I355FD61F/814C: 792B
  IF42747AA/80DD: 792B
